import math

#controller ports 
CONTROLLER_DRIVER_PORT = 1
CONTROLLER_OPERATOR_PORT = 2


#motor CAN_IDS
MOTOR_FRONT_LEFT_DRIVE_CAN_ID = 1
MOTOR_FRONT_LEFT_TURN_CAN_ID = 2
ENCODER_FRONT_LEFT_CAN_ID = 3
MOTOR_FRONT_RIGHT_DRIVE_CAN_ID = 4
MOTOR_FRONT_RIGHT_TURN_CAN_ID = 5
ENCODER_FRONT_RIGHT_CAN_ID = 6
MOTOR_REAR_LEFT_DRIVE_CAN_ID = 7
MOTOR_REAR_LEFT_TURN_CAN_ID = 8
ENCODER_REAR_LEFT_CAN_ID = 9
MOTOR_REAR_RIGHT_DRIVE_CAN_ID = 10
MOTOR_REAR_RIGHT_TURN_CAN_ID = 11
ENCODER_REAR_RIGHT_CAN_ID = 12
IMU_CAN_ID = 13